services:
  mssql:
    restart: unless-stopped
    image: mcr.microsoft.com/mssql/server:2022-CU20-ubuntu-22.04
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    volumes:
      - data:/var/opt/mssql
    ports:
      - ${APP_PORT}:1433
    networks:
      - kotakin_net

networks:
  kotakin_net:
    external: true

volumes:
  data: